dist: bionic

services:
  - docker

language: go
go:
  - "1.13.x"

install:
  - make tools

jobs:
  fast_finish: true
  include:
    - name: "Code Lint"
      script:
        - make lint
    - name: "Code UnitTest"
      script:
        - make test
    - name: "Website"
      script:
        - make website-test

script:
  - make lint
  - make test
  - make website-test

branches:
  only:
    - master
    - add-travis-ci
