dist: bionic

services:
  - docker

language: go
go:
  - "1.13.x"

install:
  - make tools

script:
  - make lint
  - make test
  - make website-test

branches:
  only:
    - master
    - add-travis-ci
